name: 110036 Scraper

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: # allows manual runs

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          cd scraper
          pip install -r requirements.txt

      - name: Run scraper
        env:
          BACKEND_API_BASE: ${{ secrets.BACKEND_API_BASE }}
          SCRAPE_INTERVAL: "60"
          HEADLESS_MODE: "true"
        run: |
          cd scraper
          python main.py --once
